# Generated by Django 4.0.6 on 2022-07-08 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'CarModel',
                'verbose_name_plural': 'CarModel',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True, verbose_name='Название')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('percent', models.PositiveSmallIntegerField(help_text='Процент производителя на товар', verbose_name='Процент')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(verbose_name='Итоговая сумма')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='car.car', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Result',
            },
        ),
        migrations.CreateModel(
            name='CarPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количества детали')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_parts', to='car.car', verbose_name='')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_parts', to='car.part', verbose_name='Деталь')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car.carmodel', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='car',
            name='parts',
            field=models.ManyToManyField(related_name='cars', through='car.CarPart', to='car.part', verbose_name='деталь'),
        ),
    ]
